### ISSUE TITLE
Allow the computer to win a match

### ISSUE THREAD

**Issue by nmalacarne** [dolmengate/stunning-invention#1]
At the moment, it is impossible for the computer to win a game of RPS against the player.

P.S.

You can close this issue directly from the commit that fixes this issue by using specific keywords in your commit message https://help.github.com/articles/closing-issues-via-commit-messages/

e.g.

Add logic to handle the computer winning

Fixes #1

**Comment by dolmengate** [comment]
Not sure of the utility of this change. Why would one want to lose?
